version: "3"

services:
  alfresco:
    image: alfresco/alfresco-content-repository-community:latest
    build: ./user-session-management-platform
    environment:
      JAVA_OPTS : "
                -Ddb.driver=org.postgresql.Driver
                -Ddb.username=alfresco
                -Ddb.password=alfresco
                -Ddb.url=jdbc:postgresql://postgres:5432/alfresco
                -Dsolr.host=solr6
                -Dsolr.port=8983
                -Dsolr.secureComms=none
                -Dsolr.base.url=/solr
                -Dindex.subsystem.name=solr6
                -Dshare.host=localhost
                -Dalfresco.port=8080
                -Daos.baseUrlOverwrite=http://localhost:8080/alfresco/aos
                -Dmessaging.broker.url=\"failover:(nio://activemq:61616)?timeout=3000&jms.useCompression=true\"
                -Ddeployment.method=DOCKER_COMPOSE
                -Dcsrf.filter.enabled=false
                -Xms1g -Xmx2g
                -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=5005
                "
    networks:
      - backend
    ports:
      - 8080:8080 #Browser port
      - 5005:5005 #Debug port

  share:
    image: alfresco/alfresco-share:6.0.c
    build: ./user-session-management-share
    environment:
      - JAVA_OPTS="-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=5006"
      - REPO_HOST=alfresco
      - REPO_PORT=8080
    ports:
      - 8081:8080
      - 5006:5006
    networks:
      - backend

  postgres:
    image: postgres:10.1
    environment:
      - POSTGRES_PASSWORD=alfresco
      - POSTGRES_USER=alfresco
      - POSTGRES_DB=alfresco
    command: postgres -c max_connections=300 -c log_min_messages=LOG
    ports:
      - 5432:5432
    networks:
      - backend

  solr6:
    image: alfresco/alfresco-search-services:1.2.0
    environment:
      #Solr needs to know how to register itself with Alfresco
      - SOLR_ALFRESCO_HOST=alfresco
      - SOLR_ALFRESCO_PORT=8080
      #Alfresco needs to know how to call solr
      - SOLR_SOLR_HOST=solr6
      - SOLR_SOLR_PORT=8983
      #Create the default alfresco and archive cores
      - SOLR_CREATE_ALFRESCO_DEFAULTS=alfresco,archive
    ports:
      - 8983:8983 #Browser port
    networks:
      - backend

  activemq:
    image: alfresco/alfresco-activemq:5.15.6
    ports:
      - 8161:8161 # Web Console
      - 5672:5672 # AMQP
      - 61616:61616 # OpenWire
      - 61613:61613 # STOMP
    networks:
      - backend

networks:
  backend:
